server:
  port: 8761
spring:
  application:
    name: SERVICE-REGISTRY
eureka:
  instance:
    hostname: "${HOSTNAME}.euraka"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
