server:
  port: 9002
spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:9296

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    DEPARTMENT-SERVICE:
      registerHealthIndicator: true
      slidingWindowSize: 100
eureka:
  instance:
    hostname: eureka-0
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
