server:
  port: 9002
spring:
  application:
    name: USER-SERVICE
  config:
    import: optional:configserver:http://localhost:9296

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

resilience4j.circuitbreaker:
  instances:
    DEPARTMENT-SERVICE:
      registerHealthIndicator: true
      slidingWindowSize: 100
